# Generated by Django 3.1.4 on 2020-12-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.TextField()),
                ('request_id', models.IntegerField(default=0)),
                ('amount', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
    ]
